materialname = "ceramic"

material = TermlistMaterial.where(name: materialname).first

material_specifieds = [
  "African Red Slip Ware (ARSW)", 
  "Cypriote Base-Ring-Ware",
  "Chocolate-on-White Ware",
  "Cypriote Red Slip Ware (CRSW)",
  "Eastern Terra Sigillata (ETS)",
  "Khirbet Kerak Ware",
  "Late Helladic (LH)",
  "Late Roman Coarse Ware (LRCW)",
  "Metal Ware",
  "porcelain",
  "pseudo-celadon",
  "Terra Sigillata (TS)",
  "White Slip Ware",
  "undetermined"]

kind_of_objects = [
  {"architectural element": 
    ["floor tile", 
     "roof tile", 
     "water pipe"]},
  "coffin",
  "coffin lid",
  "inscribed tablet",
  "knob",
  "lid",
  "ostracon",
  "sarcophagus",
  {"sculpture": 
    ["bust", 
     "figurine anthropomorphic",
     "figurine anthropomorphic-theriomorphic",
     "figurine theriomorphic",
     "mask"]},
  "spindle whorl",
  "spoon",
  {"vessel":
    ["alabastron",
     "amphora",
    "amphoriskos",
    "anthropomorphic vessel",
    "basin",
    "bottle",
    "bowl",
    "casserole",
    "chalice",
    "churn",
    "cooking pot",
    "cornet",
    "cup",
    "dish",
    "fenestrated-pedestalled bowl",
    "fish plate",
    "flask",
    "goblet",
    "holemouth vessel",
    "jar",
    "jug",
    "kernos",
    "krater",
    "lagynos",
    "lamp",   
    "pithos",
    "plate",
    "platter",
    "pyxis",
    "rhyton",
    "spouted jar",
    "stand",
    "storage jar",
    "strainer",
    "sugar bowl",
    "table amphora",
    "theomorphic vessel",
    "twin-amphoriskos",
    "twin-cup",
    "unguentarium"]}
  ]
