$excavation_site_names = [
  "Abu Nusayr",
  "Abu Habil",
  "Abu 'Alanda",
  "Jericho",
  "Petra",
  "al-Baq'ah",
  "at-Tannur",
  "al-Jubayhah",
  "al-Jufah",
  "al-Jib",
  "al-Hadadah",
  "al-Harra",
  "al-Hasa",
  "al-Khalil",
  "ad-Darbiyyat",
  "ar-Rihani",
  "adh-Dhahiryyah",
  "al-Ghassul",
  "al-Far'ah",
  "Jerusalem",
  "al-Qusur",
  "al-Qal'ah",
  "al-Qal'ah",
  "al-Kamal",
  "al-Waibdah",
  "al-Mughaiar",
  "al-Mugabalayn",
  "al-Muagar",
  "an-Nuzha",
  "al-Yadudah",
  "Umm Uthaynah",
  "Umm al-Basatin",
  "Umm al-Bighal",
  "Umm al-Khanafish",
  "Umm as-Sumaq",
  "Umm al-Qanafid",
  "Umm al-Kundum",
  "Umm al-Hawa",
  "Umm Tinah",
  "Umm Hamad",
  "Jericho",
  "Umm Tinah",
  "Busayrah",
  "Balata",
  "Bayt Aybah",
  "Bayt Ayl",
  "Bir Anbash",
  "Tall al-Far'ah",
  "Tall al-Mafjar",
  "Tall Siran",
  "Tila' al-'Ali",
  "Jawa",
  "Jabal al-Akhdar",
  "Jabal al-Jufah",
  "Jabal al-Husain",
  "Jabal 'Amman",
  "Halqa",
  "Khirbat at-Tannu",
  "Duthan",
  "Duwaylah",
  "Dhiban",
  "Rujm al-Malfuf",
  "Rujm Hani",
  "Sahab",
  "Saylat Adh-Dhahar",
  "Safut",
  "Tab Kra'",
  "Arqub Adh-Dhahar",
  "Amman",
  "Ghrubah",
  "Ghawr al-Mazra'ah",
  "Qasr at-Tuba",
  "Qwualylibah",
  "Katarat as-Samrah",
  "Kufr Qadum",
  "Kutsah",
  "Quzilfah",
  "Nablus",
  "Na'ur",
  "Wadi as-Sir"
]
