version: '3.7'
services:
  db:
    image: postgres:9.6
    ports:
            - "5432:5432"
    expose:
            - "5432"
    env_file:
            - dojam-postgres.env
    volumes:
            - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 22333 -b '0.0.0.0'
    volumes:
      - .:/dojam
    ports:
      - "22333:22333"
    depends_on:
      - db
