version: '3.7'
volumes:
  postgres-data:
services:
  db:
    image: postgres:11.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 22333 -b '0.0.0.0'
    volumes:
      - .:/dojam
    ports:
      - "22333:22333"
    depends_on:
      - db
