version: '3.6'
services:
  db:
    image: postgres:9.6
    expose:
      - "5432"
    env_file:
        - ./dojam-postgres.env
    volumes:
      - /scripts/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data
  app:
    build:
      context: .
    command: bundle exec rails s -p 22333 -b '0.0.0.0'
    volumes:
      - ./app:/dojam
    ports:
      - "22333:22333"
    depends_on:
      - db
    stdin_open: true
    tty: true
