version: '3.6'
services:
  db:
    ports:
      # Used to access the database from the IDE
      - "5556:5432"
  app:
    build:
      target: dev
    volumes:
      - ../app:/dojam
      - tmp_files:/dojam/tmp/ # For faster bootsnap
      - asset_files:/dojam/public/assets # For faster system tests / precompiled assets

    command: bundle exec rails s -p 22333 -b '0.0.0.0'
    ports:
      - "22333:22333"
volumes:
  tmp_files:
  asset_files: