version: '3.6'
services:
  db:
    ports:
      # Used to access the database from the IDE
      - "5556:5432"
  app:
    build:
      target: dev
    volumes:
      - ../app:/dojam
    command: bundle exec rails s -p 22333 -b '0.0.0.0'
    ports:
      - "22333:22333"