source 'https://rubygems.org'

gem 'i18n-active_record', :require => 'i18n/active_record'

# Used by rubymine
gem 'rubocop'

# Default since rails 6.0
#gem 'webpacker'

# Allow translation of model attributes (used for terms)
gem 'traco'

# Termlists are exported as zip file with one ms per file
gem 'rubyzip'

gem 'activeadmin'
gem 'active_admin_import'
gem 'devise'
gem 'devise-i18n'
gem 'cancancan'

# Authorization
# Used to protect main admin (id: 1) and protect termlists from users without extended access
gem 'pundit'

# Reporting with visuals
gem 'reports_kit'

# Simpliest fulltext search
gem 'search_cop'

# use postgreSQL's own fulltext search
gem 'pg_search'

# used by active storage to create thumbnail
gem 'mini_magick', '~> 4.10'

gem "image_processing", '~> 1.12'

# Reads Excel files
gem "roo", "~> 2.8"

# Writes .xls files (not xlsx!)
gem "spreadsheet", "~> 1.2.6"

# Show hashes nicely with ap method
gem "awesome_print"

# Used i.e. by importer to match columns to attributes
gem "fuzzy_match"

# helps with decorators
gem 'draper', '~> 4.0'

# needed by bootstrap gem
gem 'sprockets-rails'
gem 'bootstrap', '~> 4.4'

# will be initialized with bootstrap support
gem 'simple_form', '~> 5.0'

# creates multistep forms for models
gem 'wicked'

# Used for rails 5.2 for faster application start
gem 'bootsnap', '~> 1.4', require: false

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0'

# Rails locale data repository
gem 'rails-i18n', '~> 6.0'

# Add i18n to kaminari. ar not available as of today
gem 'kaminari-i18n'

# Use Puma as the app server
gem 'puma', '~> 4.3'

gem 'administrate'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 6.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 5.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

# DSL to build json structures
gem 'jbuilder', '~> 2.10'

# postgres
gem 'pg'

# batch import
gem 'activerecord-import', '~> 1.0'

# makes credential in config/application.yml available for rail (added to .gitignore)
gem "figaro"

# Gives sorted models
gem 'acts_as_list', '~> 1.0'

# Provides pagination
gem 'kaminari'

# html to pdf
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 11.1', platform: :mri
  gem "factory_bot_rails", '~> 5.2'
	gem 'rspec-rails'
	gem 'guard'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'rspec'
  gem 'faker'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 4.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  #gem "rails-erd" # Generate Entity-Relationship Diagrams; ToDo: Add neccessary 'dot' executable to docker container
  gem 'scout_apm', '~> 2.6' # used for profiling
  gem 'rack-mini-profiler', '~> 2.0' # also profiling
  gem 'memory_profiler', '~> 0.9' # For memory profiling used by rack-mini-profiler
  # For call-stack profiling flamegraphs used by rack-mini-profiler
  gem 'flamegraph'
  gem 'stackprof'
	gem 'ruby-prof'
  gem 'i18n-tasks', '~> 0.9.31'
end
