class RenameTermlistKindOfObjectSpecifiedsIdFromTermlistKindOfObjectSpecifiedsDatingCenturies < ActiveRecord::Migration[5.0]
  def change
  rename_column :termlist_kind_of_object_specifieds_dating_centuries, :termlist_kind_of_object_specifieds_id, :termlist_kind_of_object_specified_id
  end
end
