#!/bin/bash
set -e

psql <<-EOSQL
    CREATE USER dojam WITH PASSWORD '$DOJAM_DB_PASSWORD';
    ALTER USER dojam CREATEDB;
    CREATE USER "TEST_dojam" WITH PASSWORD '000000000000';
    ALTER USER "TEST_dojam" CREATEDB;
    CREATE DATABASE "DOJAM_DB" OWNER dojam;
    CREATE DATABASE "TEST_DB" OWNER "TEST_dojam";
EOSQL
