#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE USER dojam WITH PASSWORD '$DOJAM_DB_PASSWORD';
    ALTER USER dojam CREATEDB;
    CREATE USER "TEST_dojam" WITH PASSWORD '000000000000';
    ALTER USER "TEST_dojam" CREATEDB;
EOSQL
