class TermlistDecorationTechnique < ApplicationRecord
  has_many :termlist_kind_of_object_specifieds_decoration_techniques
  has_many :termlist_kind_of_object_specifieds, through: :termlist_kind_of_object_specifieds_decoration_techniques
  has_many :museum_objects
end
