class TermlistProductionTechnique < ApplicationRecord
  has_many :termlist_kind_of_object_specifieds_production_techniques
  has_many :termlist_kind_of_objects, through: :termlist_kind_of_object_specifieds_production_techniques
  has_many :museum_objects
end
