require "administrate/base_dashboard"

class MuseumObjectDashboard < Administrate::BaseDashboard
	def display_resource(resource)
		resource.inv_number	
	end
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    images: Field::String.with_options(searchable: false),
    excavation_site: Field::BelongsTo,
    storage_location: Field::BelongsTo,
    termlist_acquisition_delivered_by: Field::BelongsTo,
    termlist_acquisition_kind: Field::BelongsTo,
    termlist_authenticity: Field::BelongsTo,
    termlist_dating_millennium: Field::BelongsTo,
    termlist_dating_period: Field::BelongsTo,
    termlist_kind_of_object: Field::BelongsTo,
    termlist_kind_of_object_specified: Field::BelongsTo,
    termlist_production_technique: Field::BelongsTo,
    termlist_decoration_technique: Field::BelongsTo,
    termlist_decoration_color: Field::BelongsTo,
    termlist_decoration: Field::BelongsTo,
    termlist_preservation_material: Field::BelongsTo,
    termlist_preservation_object: Field::BelongsTo,
    termlist_inscription_letter: Field::BelongsTo,
    termlist_inscription_language: Field::BelongsTo,
    termlist_excavation_site_kind: Field::BelongsTo,
    main_material_specified: Field::BelongsTo.with_options(class_name: "TermlistMaterialSpecified"),
    join_museum_object_material_specifieds: Field::HasMany,
    termlist_material_specifieds: Field::HasMany,
    material_specifieds_koo_specs: Field::HasMany,
    possible_production_techniques: Field::HasMany.with_options(class_name: "TermlistProductionTechnique"),
    termlist_production_techniques: Field::HasMany,
    termlist_materials: Field::HasMany,
    join_museum_object_colors: Field::HasMany,
    termlist_colors: Field::HasMany,
    join_museum_object_dating_centuries: Field::HasMany,
    termlist_dating_centuries: Field::HasMany,
    id: Field::Number,
    inv_number: Field::String,
    inv_extension: Field::Number,
    inv_numberdoa: Field::String,
    amount: Field::Number,
    finding_context: Field::String,
    finding_remarks: Field::Text,
    description_authenticities_name: Field::String,
    description_conservation: Field::String,
    description_preservation_state_name: Field::String,
    acquisition_deliverer_name: Field::String,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
    acquisition_date: Field::DateTime,
    is_finished: Field::Boolean,
    inscription_decoration: Field::String,
    inscription_text: Field::String,
    inscription_translation: Field::String,
    priority: Field::Number,
    priority_determined_by: Field::String,
    max_length: Field::Number.with_options(decimals: 2),
    max_width: Field::Number.with_options(decimals: 2),
    height: Field::Number.with_options(decimals: 2),
    opening_dm: Field::Number.with_options(decimals: 2),
    bottom_dm: Field::Number.with_options(decimals: 2),
    weight_in_gram: Field::Number.with_options(decimals: 2),
    remarks: Field::Text,
    literature: Field::Text,
    acquisition_document_number: Field::String,
    name_mega_jordan: Field::String,
    name_expedition: Field::String,
    site_number_mega: Field::String,
    site_number_jadis: Field::String,
    site_number_expedition: Field::String,
    coordinates_mega: Field::String,
    dating_timespan_begin: Field::DateTime,
    dating_timespan_end: Field::DateTime,
    images: Field::String.with_options(searchable: false),
    is_used: Field::Boolean,
    current_build_step: Field::String,
    acquisition_date_precision: Field::Number,
    coordinates_mega_long: Field::String,
    coordinates_mega_lat: Field::String,
    munsell_color: Field::String,
    needs_cleaning: Field::Boolean,
    needs_conservation: Field::Boolean,
    is_dating_timespan_begin_BC: Field::Boolean,
    is_dating_timespan_end_BC: Field::Boolean,
    main_material_specified_id: Field::Number,
    termlist_material_specified_id: Field::Number,
  }.freeze

  # COLLECTION_ATTRIBUTES
  # an array of attributes that will be displayed on the model's index page.
  #
  # By default, it's limited to four items to reduce clutter on index pages.
  # Feel free to add, remove, or rearrange items.
  COLLECTION_ATTRIBUTES = [
    :images,
    :excavation_site,
    :storage_location,
    :termlist_acquisition_delivered_by,
  ].freeze

  # SHOW_PAGE_ATTRIBUTES
  # an array of attributes that will be displayed on the model's show page.
  SHOW_PAGE_ATTRIBUTES = [
    :images,
    :excavation_site,
    :storage_location,
    :termlist_acquisition_delivered_by,
    :termlist_acquisition_kind,
    :termlist_authenticity,
    :termlist_dating_millennium,
    :termlist_dating_period,
    :termlist_kind_of_object,
    :termlist_kind_of_object_specified,
    :termlist_production_technique,
    :termlist_decoration_technique,
    :termlist_decoration_color,
    :termlist_decoration,
    :termlist_preservation_material,
    :termlist_preservation_object,
    :termlist_inscription_letter,
    :termlist_inscription_language,
    :termlist_excavation_site_kind,
    :main_material_specified,
    :join_museum_object_material_specifieds,
    :termlist_material_specifieds,
    :material_specifieds_koo_specs,
    :possible_production_techniques,
    :termlist_production_techniques,
    :termlist_materials,
    :join_museum_object_colors,
    :termlist_colors,
    :join_museum_object_dating_centuries,
    :termlist_dating_centuries,
    :id,
    :inv_number,
    :inv_extension,
    :inv_numberdoa,
    :amount,
    :finding_context,
    :finding_remarks,
    :description_authenticities_name,
    :description_conservation,
    :description_preservation_state_name,
    :acquisition_deliverer_name,
    :created_at,
    :updated_at,
    :acquisition_date,
    :is_finished,
    :inscription_decoration,
    :inscription_text,
    :inscription_translation,
    :priority,
    :priority_determined_by,
    :max_length,
    :max_width,
    :height,
    :opening_dm,
    :bottom_dm,
    :weight_in_gram,
    :remarks,
    :literature,
    :acquisition_document_number,
    :name_mega_jordan,
    :name_expedition,
    :site_number_mega,
    :site_number_jadis,
    :site_number_expedition,
    :coordinates_mega,
    :dating_timespan_begin,
    :dating_timespan_end,
    :images,
    :is_used,
    :current_build_step,
    :acquisition_date_precision,
    :coordinates_mega_long,
    :coordinates_mega_lat,
    :munsell_color,
    :needs_cleaning,
    :needs_conservation,
    :is_dating_timespan_begin_BC,
    :is_dating_timespan_end_BC,
    :main_material_specified_id,
    :termlist_material_specified_id,
  ].freeze

  # FORM_ATTRIBUTES
  # an array of attributes that will be displayed
  # on the model's form (`new` and `edit`) pages.
  FORM_ATTRIBUTES = [
    :images,
    :excavation_site,
    :storage_location,
    :termlist_acquisition_delivered_by,
    :termlist_acquisition_kind,
    :termlist_authenticity,
    :termlist_dating_millennium,
    :termlist_dating_period,
    :termlist_kind_of_object,
    :termlist_kind_of_object_specified,
    :termlist_production_technique,
    :termlist_decoration_technique,
    :termlist_decoration_color,
    :termlist_decoration,
    :termlist_preservation_material,
    :termlist_preservation_object,
    :termlist_inscription_letter,
    :termlist_inscription_language,
    :termlist_excavation_site_kind,
    :main_material_specified,
    :join_museum_object_material_specifieds,
    :termlist_material_specifieds,
    :material_specifieds_koo_specs,
    :possible_production_techniques,
    :termlist_production_techniques,
    :termlist_materials,
    :join_museum_object_colors,
    :termlist_colors,
    :join_museum_object_dating_centuries,
    :termlist_dating_centuries,
    :inv_number,
    :inv_extension,
    :inv_numberdoa,
    :amount,
    :finding_context,
    :finding_remarks,
    :description_authenticities_name,
    :description_conservation,
    :description_preservation_state_name,
    :acquisition_deliverer_name,
    :acquisition_date,
    :is_finished,
    :inscription_decoration,
    :inscription_text,
    :inscription_translation,
    :priority,
    :priority_determined_by,
    :max_length,
    :max_width,
    :height,
    :opening_dm,
    :bottom_dm,
    :weight_in_gram,
    :remarks,
    :literature,
    :acquisition_document_number,
    :name_mega_jordan,
    :name_expedition,
    :site_number_mega,
    :site_number_jadis,
    :site_number_expedition,
    :coordinates_mega,
    :dating_timespan_begin,
    :dating_timespan_end,
    :images,
    :is_used,
    :current_build_step,
    :acquisition_date_precision,
    :coordinates_mega_long,
    :coordinates_mega_lat,
    :munsell_color,
    :needs_cleaning,
    :needs_conservation,
    :is_dating_timespan_begin_BC,
    :is_dating_timespan_end_BC,
    :main_material_specified_id,
    :termlist_material_specified_id,
  ].freeze

  # Overwrite this method to customize how museum objects are displayed
  # across all pages of the admin dashboard.
  #
  # def display_resource(museum_object)
  #   "MuseumObject ##{museum_object.id}"
  # end
end
